### ISSUE TITLE
Track time and RAM used for executing an exercise

### ISSUE THREAD

**Issue by Leomeror** [jlab/bellmanscafe#13]
Track time and RAM and display it on the website

**Comment by sjanssen2** [comment]
rudimentary introduced in #53 , but results are not used yet

**Comment by sjanssen2** [comment]
now (with PR #54 ) being displayed as light gray information at the bottom of each command results, like:
![image](https://github.com/jlab/bellmanscafe/assets/11960616/44bebfd8-d4fe-4b8b-a379-c45bf6083fc2)
